#!/bin/bash

### This script is called after the user installs the application.
export PATH=/var/apps/python312/target/bin:$PATH


cd ../app/server

# 创建虚拟环境
python3 -m venv .venv

# 激活虚拟环境
source .venv/bin/activate

# 安装 python 相关依赖到 .venv
pip install -r requirements.txt


exit 0